{"name": "编辑用户手机号为异常号码", "status": "passed", "description": "编辑用户手机号为异常号码", "attachments": [{"name": "log", "source": "d9a0ebd1-5bbd-4f25-8db5-a2ef899b77dd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '编辑用户手机号为异常号码', 'nickname': '刘子编辑', 'phone': 1595485421655, 'real_name': '刘子编辑', 'identities': 5, 'gender': 2, 'stu_no': 9658}"}], "start": 1723781060979, "stop": 1723781061257, "uuid": "4b13b189-99b6-4650-8158-279304ab5088", "historyId": "2ad69d55c68046fabfdd9b7bea2e5879", "testCaseId": "f83ac5b0bdd72330d7bfd52b3edea55e", "fullName": "testcases.test_user_manage_api.TestUserManageApi#test_edit_user_abnormal", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "编辑用户手机号为异常号码测试用例"}, {"name": "feature", "value": "用户管理模块"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user_manage_api"}, {"name": "subSuite", "value": "TestUserManageApi"}, {"name": "host", "value": "常胜峰"}, {"name": "thread", "value": "24432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user_manage_api"}]}